### ISSUE TITLE
Le but de cette issue est de tester Element X

### ISSUE THREAD

**Issue by stephane-klein** [harobed/personnal-notebook#297]
Le but de cette issue est de tester [Element X](https://element.io/blog/element-x-experience-the-future-of-element/).

**Comment by stephane-klein** [comment]
@Its-Alex Pour le moment Element X est limité à iOS.

Je pensais qu'il y avait une version "Element X" pour Desktop, mais ce n'est pas le cas.

**Comment by Its-Alex** [comment]
@stephane-klein Bientôt mais pas encore :sweat_smile:

**Comment by stephane-klein** [comment]
https://element.io/blog/element-x-android-preview/

Cc @Its-Alex
