### ISSUE TITLE
Problème MAIN_ROUNDOFTOTAL_NOT_TOTALOFROUND à 1 et arrondis à 0

### ISSUE THREAD

**Issue by Hekang100** [harobed/personnal-notebook#303]
Lorsque MAIN_ROUNDOFTOTAL_NOT_TOTALOFROUND est positionné à 1, le Nombre de décimales maximum pour les prix unitaires ainsi que Nombre de décimales maximum pour les prix totaux à 0 (pas de décimales utilisées pour les prix dans le pays où j'habite) et que j'ajoute des produits dans une commande ou sur une facture, j'obtiens l'erreur suivante :
This website or feature is currently temporarly not available or failed after a technical error.
This may be due to a maintenance operation. Current status of operation (2023-08-27T11:19:47Z) are on next line...
Dolibarr a détecté une erreur technique. Vous pouvez lire le fichier log ou définir l'option $dolibarr_main_prod sur '0' dans votre fichier de configuration pour obtenir plus d'informations.

J'utilise Dolibarr 17.0.2

**Comment by stephane-klein** [comment]
@Hekang100 Je ne comprends pas le contexte de cette issue.

Pouvez-vous en dire plus ?
